// ss_hook_mac -- the macOS capture dylib: the cross-platform sibling of dll/ss_hook.cpp.
//
// Injected into each stock Zandronum client via DYLD_INSERT_LIBRARIES (set by host/ss_proc.h when it
// spawns the client). It does the same job as the Windows DLL on a portable stack:
//
//   capture   : DYLD_INTERPOSE SDL_GL_SwapWindow -- each frame glReadPixels the GL back buffer and
//               publish it to POSIX shared memory "ZanDLLFB_<pid>" (the host composites it).
//   input     : read the host's "ZanIN_<pid>" channel and replay it through the engine's own
//               D_PostEvent (resolved from the Mach-O), so the engine does binds / menu / look with
//               this client's config -- identical event protocol to the Windows hook.
//   hide      : DYLD_INTERPOSE SDL_CreateWindow (force SDL_WINDOW_HIDDEN) + SDL_ShowWindow (no-op),
//               so only the compositor is visible and a hidden client never steals focus.
//   symbols   : engine functions/globals are (Mach-O image slide + the symbol's vmaddr from
//               ss_offsets.h, generated by tools/gen_offsets_mac.cpp).
//
// The mac engine is SDL2-based (GZDoom/Zandronum family), so SDL_GL_SwapWindow is the present hook and
// SDL_CreateWindow is where the window is born -- both reached cleanly by dyld interposing (no MinHook).
//
// LIMITATION (v1): native per-seat controller AXES (the Windows I_GetAxes inline-hook) are NOT ported --
// that needs an inline function patch (interposing only reaches dynamic symbols, and I_GetAxes is
// internal). Keyboard, mouse, and controller BUTTONS work (they go through D_PostEvent). Analog stick
// movement per seat is a follow-up (a small x86_64 trampoline or a hooking lib like Dobby).
//
// Runtime needs a Mac + the Intel engine + real offsets (gen_offsets_mac). CI verifies it COMPILES.
#include <SDL.h>
#include <OpenGL/gl.h>
#include <mach-o/dyld.h>
#include <mach-o/loader.h>
#include <pthread.h>
#include <unistd.h>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "../host/ss_shm.h"
#include "ss_offsets.h"   // generated at build time: SS_RVA_<name> = the symbol's Mach-O vmaddr

#ifndef GL_BGRA
#define GL_BGRA 0x80E1
#endif

namespace {

// --- shared-memory protocol (MUST match dll/ss_hook.cpp + the host) -------------------------------
const int32_t FB_MAGIC = 0x5A444C46;   // 'ZDLF'
const int32_t IN_MAGIC = 0x5A414E49;   // 'ZANI'
const int IN_BYTES   = 1024;
const int KEY_RING   = 64;
const int IN_AXES    = 136;            // 5 axes (host writes value x1000)
const int IN_MENU    = 160;            // DLL writes back: 1 = this seat is in a menu/console
const int IN_CMDSEQ  = 164;            // host bumps after writing a console command at IN_CMDTEXT
const int IN_CMDTEXT = 168;
const int IN_CMDMAX  = 120;
const int NUM_JOYAXIS = 5;
enum { SC_GRAVE = 0x29, KEY_MOUSE1 = 0x100, KEY_MOUSE3 = 0x102 };

// event_t mirrors d_event.h at default alignment: type@0 subtype@1 data1/2/3@2/4/6 x@8 y@12.
struct EngEvent { unsigned char type, subtype; short data1, data2, data3; int x, y; };
enum { EV_KeyDown = 1, EV_KeyUp = 2, EV_Mouse = 3, EV_GUI_Event = 4 };
enum { GUI_KeyDown = 1, GUI_KeyUp = 3, GUI_Char = 4,
       GUI_MouseMove = 6, GUI_LBtnDown = 7, GUI_LBtnUp = 8,
       GUI_MBtnDown = 10, GUI_MBtnUp = 11, GUI_RBtnDown = 13, GUI_RBtnUp = 14 };

typedef void (*PostEvent_t)(const EngEvent*);
typedef void (*AddCmd_t)(char*, int);
PostEvent_t    g_postEvent    = nullptr;
AddCmd_t       g_addCmd       = nullptr;
int*           g_menuActive   = nullptr;
int*           g_consoleState = nullptr;
unsigned char* g_guiCapture   = nullptr;
unsigned int*  g_chatMode     = nullptr;
volatile int*  g_appActive    = nullptr;
int32_t        g_cmdSeq       = 0;

// framebuffer (we create) + input (host creates; we open RW)
ss::ShmView    g_fbShm;
unsigned char* g_view = nullptr;
size_t         g_size = 0;
int            g_frame = 0;
ss::ShmView    g_inShm;
volatile int32_t* g_in = nullptr;
int            g_keyRead = 0;

// virtual GUI cursor (use_mouse 0 kills the engine's native cursor; we feed EV_GUI_MouseMove)
int  g_vpW = 640, g_vpH = 360, g_curX = 320, g_curY = 180;
bool g_guiWas = false;
bool g_invMouseY = false;

// atomically take + zero a host-written delta (host adds, we consume each frame)
inline int TakeDelta(volatile int32_t* p) { return __atomic_exchange_n(p, 0, __ATOMIC_SEQ_CST); }

// --- input: read the host's channel and replay it as engine events (mirrors ss_hook.cpp ApplyInput) -
void ApplyInput() {
    if (g_in == nullptr) {
        char nm[64]; snprintf(nm, sizeof(nm), "ZanIN_%d", (int)getpid());
        g_inShm = ss::ShmOpenRW(nm);
        if (!g_inShm.ptr) return;                       // host hasn't created it yet
        g_in = (volatile int32_t*)g_inShm.ptr;
        g_keyRead = g_in[5];
        g_cmdSeq  = g_in[IN_CMDSEQ];
    }
    if (g_in[0] != IN_MAGIC || !g_postEvent) return;

    if (g_addCmd) {                                     // runtime console command channel (music handoff)
        int32_t seq = g_in[IN_CMDSEQ];
        if (seq != g_cmdSeq) {
            g_cmdSeq = seq;
            char cmd[IN_CMDMAX];
            memcpy(cmd, (const void*)(g_in + IN_CMDTEXT), IN_CMDMAX);
            cmd[IN_CMDMAX - 1] = '\0';
            if (cmd[0]) g_addCmd(cmd, 0);
        }
    }

    bool menuOpen = (g_menuActive && *g_menuActive != 0);
    int  cs = (g_consoleState ? *g_consoleState : 0);
    bool guiOpen = (g_guiCapture && *g_guiCapture != 0) || (g_chatMode && *g_chatMode != 0)
                 || menuOpen || cs == 1 || cs == 2;
    if (guiOpen && !g_guiWas) { g_curX = g_vpW / 2; g_curY = g_vpH / 2; }
    g_guiWas = guiOpen;
    g_in[IN_MENU] = guiOpen ? 1 : 0;                    // publish: this seat is in a menu -> host frees the mouse

    int dx = TakeDelta(&g_in[3]);                       // consume raw per-frame deltas
    int dy = TakeDelta(&g_in[4]);
    if (dx || dy) {
        if (guiOpen) {                                  // drive the GUI cursor (absolute pixels)
            int rawdy = g_invMouseY ? dy : -dy;
            g_curX += dx;    if (g_curX < 0) g_curX = 0; if (g_curX > g_vpW) g_curX = g_vpW;
            g_curY += rawdy; if (g_curY < 0) g_curY = 0; if (g_curY > g_vpH) g_curY = g_vpH;
            EngEvent ev = {}; ev.type = EV_GUI_Event; ev.subtype = GUI_MouseMove;
            ev.data1 = (short)g_curX; ev.data2 = (short)g_curY;
            g_postEvent(&ev);
        } else {                                        // look drives gameplay (match native x4 prescale)
            EngEvent ev = {}; ev.type = EV_Mouse; ev.x = dx << 2; ev.y = dy;
            g_postEvent(&ev);
        }
    }

    int keyWrite = g_in[5];
    if (keyWrite - g_keyRead > KEY_RING) g_keyRead = keyWrite - KEY_RING;
    for (int guard = 0; g_keyRead != keyWrite && guard < KEY_RING; ++guard, ++g_keyRead) {
        int base = 8 + (g_keyRead % KEY_RING) * 2;
        int a = g_in[base], b = g_in[base + 1];
        int down = a & 1, sc = (a >> 1) & 0x7fff, gk = b & 0xffff, ch = (b >> 16) & 0xffff;
        int raw = (a >> 16) & 1;
        bool mouseBtn = (sc >= KEY_MOUSE1 && sc <= KEY_MOUSE3);
        if (raw) {                                      // controller button -> raw EV_Key (engine routes it)
            EngEvent ev = {}; ev.type = (unsigned char)(down ? EV_KeyDown : EV_KeyUp); ev.data1 = (short)sc;
            g_postEvent(&ev);
        } else if (sc == SC_GRAVE) {                    // console toggle, always raw
            EngEvent ev = {}; ev.type = (unsigned char)(down ? EV_KeyDown : EV_KeyUp); ev.data1 = (short)sc;
            g_postEvent(&ev);
        } else if (guiOpen) {                           // keyboard/mouse drive the UI
            if (mouseBtn) {
                int dn = (sc == KEY_MOUSE1) ? GUI_LBtnDown : (sc == KEY_MOUSE3) ? GUI_MBtnDown : GUI_RBtnDown;
                int up = (sc == KEY_MOUSE1) ? GUI_LBtnUp   : (sc == KEY_MOUSE3) ? GUI_MBtnUp   : GUI_RBtnUp;
                EngEvent ev = {}; ev.type = EV_GUI_Event; ev.subtype = (unsigned char)(down ? dn : up);
                ev.data1 = (short)g_curX; ev.data2 = (short)g_curY;
                g_postEvent(&ev);
            } else {
                if (gk) {
                    EngEvent ev = {}; ev.type = EV_GUI_Event;
                    ev.subtype = (unsigned char)(down ? GUI_KeyDown : GUI_KeyUp);
                    ev.data1 = (short)gk; ev.data2 = (short)gk;
                    g_postEvent(&ev);
                }
                if (ch && down) {
                    EngEvent ev = {}; ev.type = EV_GUI_Event; ev.subtype = GUI_Char; ev.data1 = (short)ch;
                    g_postEvent(&ev);
                }
            }
        } else if (sc) {                                // gameplay binds: move/weapons/fire
            EngEvent ev = {}; ev.type = (unsigned char)(down ? EV_KeyDown : EV_KeyUp);
            ev.data1 = (short)sc; ev.data2 = (short)ch;
            g_postEvent(&ev);
        }
    }
}

// --- framebuffer publish: glReadPixels the GL back buffer into POSIX shared memory ----------------
void Publish(int w, int h) {
    size_t need = 16 + (size_t)w * h * 4;               // BGRA so the host uploads straight to a GPU texture
    if (!g_fbShm.ptr || g_size < need) {
        ss::ShmClose(g_fbShm);
        char nm[64]; snprintf(nm, sizeof(nm), "ZanDLLFB_%d", (int)getpid());
        g_fbShm = ss::ShmCreate(nm, need);
        g_view = (unsigned char*)g_fbShm.ptr;
        if (!g_view) { g_size = 0; return; }
        g_size = need;
    }
    glReadBuffer(GL_BACK);
    glPixelStorei(GL_PACK_ALIGNMENT, 1);
    glReadPixels(0, 0, w, h, GL_BGRA, GL_UNSIGNED_BYTE, g_view + 16);   // BGRA, bottom-up
    int32_t* hdr = (int32_t*)g_view;
    hdr[1] = w; hdr[2] = h; hdr[3] = ++g_frame;
    hdr[0] = FB_MAGIC;                                  // written last so a reader never sees a torn header
}

// --- engine symbol resolution: Mach-O image slide + the vmaddr baked into ss_offsets.h ------------
intptr_t MainImageSlide() {
    uint32_t n = _dyld_image_count();
    for (uint32_t i = 0; i < n; ++i) {
        const struct mach_header* mh = _dyld_get_image_header(i);
        if (mh && mh->filetype == MH_EXECUTE) return _dyld_get_image_vmaddr_slide(i);
    }
    return _dyld_get_image_vmaddr_slide(0);
}
void ResolveSymbols() {
    intptr_t slide = MainImageSlide();
    g_postEvent    = (PostEvent_t)((uintptr_t)SS_RVA_D_PostEvent     + slide);
    g_menuActive   = (int*)((uintptr_t)SS_RVA_menuactive            + slide);
    g_consoleState = (int*)((uintptr_t)SS_RVA_ConsoleState          + slide);
    g_guiCapture   = (unsigned char*)((uintptr_t)SS_RVA_GUICapture  + slide);
    g_chatMode     = (unsigned int*)((uintptr_t)SS_RVA_g_ulChatMode + slide);
    g_appActive    = (volatile int*)((uintptr_t)SS_RVA_AppActive    + slide);
    g_addCmd       = (AddCmd_t)((uintptr_t)SS_RVA_AddCommandString  + slide);
    g_invMouseY    = (getenv("SS_MOUSE_INVY") != nullptr);
}

void* KeepAliveThread(void*) {                          // hold the engine "active" so a hidden client keeps rendering
    for (;;) { if (g_appActive) *g_appActive = 1; usleep(8000); }
    return nullptr;
}

} // namespace

// --- interposed SDL entry points -----------------------------------------------------------------
// DYLD_INTERPOSE: replace references to an SDL symbol with ours; calling the original by name inside the
// replacement reaches the real implementation (dyld does not redirect the interposer's own call).
#define DYLD_INTERPOSE(_repl, _replee) \
    __attribute__((used)) static struct { const void* repl; const void* replee; } \
    _interpose_##_replee __attribute__((section("__DATA,__interpose"))) = \
    { (const void*)(uintptr_t)&_repl, (const void*)(uintptr_t)&_replee };

extern "C" void ss_SDL_GL_SwapWindow(SDL_Window* win) {
    GLint vp[4] = { 0, 0, 0, 0 };
    glGetIntegerv(GL_VIEWPORT, vp);
    int w = vp[2], h = vp[3];
    if (w > 0 && h > 0 && w <= 8192 && h <= 8192) {
        g_vpW = w; g_vpH = h;
        Publish(w, h);
    }
    ApplyInput();
    SDL_GL_SwapWindow(win);   // the real one
}
DYLD_INTERPOSE(ss_SDL_GL_SwapWindow, SDL_GL_SwapWindow)

extern "C" SDL_Window* ss_SDL_CreateWindow(const char* title, int x, int y, int w, int h, Uint32 flags) {
    return SDL_CreateWindow(title, x, y, w, h, flags | SDL_WINDOW_HIDDEN);   // born hidden
}
DYLD_INTERPOSE(ss_SDL_CreateWindow, SDL_CreateWindow)

extern "C" void ss_SDL_ShowWindow(SDL_Window* win) { (void)win; }   // keep it hidden
DYLD_INTERPOSE(ss_SDL_ShowWindow, SDL_ShowWindow)

// --- entry: the dylib's constructor runs before the engine's main() (dyld loads us first) ---------
__attribute__((constructor)) static void ss_hook_mac_init() {
    ResolveSymbols();
    pthread_t t;
    pthread_create(&t, nullptr, KeepAliveThread, nullptr);
    pthread_detach(t);
}
