// GENERATED by gen_offsets -- do not edit.
// RVA of each engine symbol; the DLL resolves it as (exe module base + RVA).
#pragma once
#define SS_RVA_D_PostEvent 0x1F0C30UL
#define SS_RVA_menuactive 0x2392580UL
