// gen_offsets -- build-time engine-symbol RVA extractor.
//
// Reads a *built* zandronum.exe (+ its .pdb sitting next to it) and writes ss_offsets.h with the
// RVA (offset from the module base) of each requested symbol. The injected DLL then resolves each
// at runtime as (GetModuleHandle(exe) + RVA) -- deterministic and instant, with NO runtime DbgHelp
// (which proved flaky: it races/colludes with the engine's own DbgHelp use).
//
// Because we always build the engine ourselves, the exe + pdb are available at DLL-build time and
// are always in sync with the DLL. If a symbol was renamed/removed upstream, this FAILS THE BUILD
// loudly here -- the single place that knows about engine internals.
//
//   gen_offsets <zandronum.exe> <out\ss_offsets.h> <symbol> [symbol ...]
#include <windows.h>
#include <dbghelp.h>
#include <cstdio>
#include <cstdint>

int main(int argc, char** argv) {
    if (argc < 4) { fprintf(stderr, "usage: gen_offsets <exe> <out.h> <symbol>...\n"); return 2; }
    const char* exe = argv[1];
    const char* outPath = argv[2];

    HANDLE proc = GetCurrentProcess();
    SymSetOptions(SYMOPT_UNDNAME | SYMOPT_EXACT_SYMBOLS);
    if (!SymInitialize(proc, NULL, FALSE)) {
        fprintf(stderr, "gen_offsets: SymInitialize failed: %lu\n", GetLastError());
        return 1;
    }
    const DWORD64 BASE = 0x10000000;
    DWORD64 modBase = SymLoadModuleEx(proc, NULL, exe, NULL, BASE, 0, NULL, 0);
    if (modBase == 0) {
        fprintf(stderr, "gen_offsets: cannot load symbols for '%s': %lu (is zandronum.pdb next to it?)\n",
                exe, GetLastError());
        return 1;
    }

    FILE* out = fopen(outPath, "w");
    if (!out) { fprintf(stderr, "gen_offsets: cannot write %s\n", outPath); return 1; }
    fprintf(out, "// GENERATED by gen_offsets -- do not edit.\n");
    fprintf(out, "// RVA of each engine symbol; the DLL resolves it as (exe module base + RVA).\n");
    fprintf(out, "#pragma once\n");

    char buf[sizeof(SYMBOL_INFO) + 512] = { 0 };
    SYMBOL_INFO* si = (SYMBOL_INFO*)buf;
    si->SizeOfStruct = sizeof(SYMBOL_INFO);
    si->MaxNameLen = 511;
    int missing = 0;
    for (int i = 3; i < argc; ++i) {
        if (SymFromName(proc, argv[i], si)) {
            unsigned long rva = (unsigned long)(si->Address - modBase);
            fprintf(out, "#define SS_RVA_%s 0x%lXUL\n", argv[i], rva);
            printf("  %-22s RVA 0x%lX\n", argv[i], rva);
        } else {
            fprintf(stderr, "gen_offsets: ERROR symbol '%s' not found in %s\n", argv[i], exe);
            ++missing;
        }
    }
    fclose(out);
    SymCleanup(proc);
    if (missing) { fprintf(stderr, "gen_offsets: %d symbol(s) missing -- aborting build.\n", missing); return 1; }
    return 0;
}
