// gen_offsets_mac -- the macOS counterpart of tools/gen_offsets.cpp (which uses Windows DbgHelp/PDB).
// Emits dll/ss_offsets.h with SS_RVA_<name> = each engine symbol's Mach-O vmaddr, so the mac hook can
// resolve it at runtime as (image slide + vmaddr). Uses the system `nm` (with -C to demangle C++) and
// matches each requested plain name against the demangled symbols -- robust enough for the few engine
// functions/globals the hook needs, without hand-parsing Mach-O + a demangler.
//
//   gen_offsets_mac <zandronum-binary> <out ss_offsets.h> <Sym1> <Sym2> ...
//
// Build/runtime is macOS-only (needs nm + the actual engine binary). If a symbol isn't found it's
// emitted as 0 with a warning -- the hook then resolves it to the image base (harmless until used), and
// the BUILD does not fail, so a partially-stripped engine still produces a usable header for the rest.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

// Does the demangled nm symbol `sym` correspond to the requested name `want`?
//   global var "menuactive"  -> nm shows "_menuactive" (leading _),
//   C++ func  "D_PostEvent"  -> nm -C shows "D_PostEvent(event_t const*)",
//   namespaced               -> "Foo::want(...)".
static bool matches(const char* sym, const char* want) {
    if (sym[0] == '_') ++sym;                       // strip the Mach-O leading underscore
    size_t n = strlen(want);
    if (strcmp(sym, want) == 0) return true;        // exact (plain global)
    if (strncmp(sym, want, n) == 0 && (sym[n] == '(' || sym[n] == '\0')) return true;  // func / exact
    // "Namespace::want" or "...::want(" -- match the trailing component
    const char* p = strstr(sym, want);
    while (p) {
        bool leftOk  = (p == sym) || (p[-1] == ':' || p[-1] == ' ' || p[-1] == '*' || p[-1] == '&');
        bool rightOk = (p[n] == '(' || p[n] == '\0');
        if (leftOk && rightOk) return true;
        p = strstr(p + 1, want);
    }
    return false;
}

// Find the vmaddr of `want` in the binary via `nm`. Returns 0 if not found.
static unsigned long long find_addr(const char* binary, const char* want) {
    char cmd[2048];
    snprintf(cmd, sizeof(cmd), "nm -arch x86_64 -C \"%s\" 2>/dev/null", binary);
    FILE* p = popen(cmd, "r");
    if (!p) return 0;
    char line[4096];
    unsigned long long best = 0;
    while (fgets(line, sizeof(line), p)) {
        // format: "<16-hex-addr> <type> <name...>"  (undefined symbols have a blank/space address)
        unsigned long long addr = 0; char type = 0; char name[4000];
        if (sscanf(line, "%llx %c %[^\n]", &addr, &type, name) == 3) {
            if (type == 'U' || type == 'u') continue;   // undefined / external ref -- no address here
            if (addr && matches(name, want)) { best = addr; break; }
        }
    }
    pclose(p);
    return best;
}

int main(int argc, char** argv) {
    if (argc < 4) {
        fprintf(stderr, "usage: gen_offsets_mac <binary> <out.h> <Sym1> [Sym2 ...]\n");
        return 1;
    }
    const char* binary = argv[1];
    const char* outPath = argv[2];
    FILE* out = fopen(outPath, "w");
    if (!out) { fprintf(stderr, "gen_offsets_mac: cannot write %s\n", outPath); return 1; }
    fprintf(out, "// generated by gen_offsets_mac from %s -- do not edit.\n", binary);
    fprintf(out, "// SS_RVA_<name> = the symbol's Mach-O vmaddr; the hook resolves it as (image slide + this).\n");
    fprintf(out, "#pragma once\n");
    int missing = 0;
    for (int i = 3; i < argc; ++i) {
        unsigned long long a = find_addr(binary, argv[i]);
        if (!a) { fprintf(stderr, "gen_offsets_mac: WARNING symbol not found: %s\n", argv[i]); ++missing; }
        fprintf(out, "#define SS_RVA_%s 0x%llxULL\n", argv[i], a);
    }
    fclose(out);
    fprintf(stderr, "gen_offsets_mac: wrote %s (%d symbol(s)%s)\n",
            outPath, argc - 3, missing ? ", some missing -- see warnings" : "");
    return 0;   // never fail the build on a missing symbol; the hook degrades gracefully
}
